In [82]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, recall_score, precision_score, confusion_matrix

In [83]:
# Para que se vean todas las columnas
pd.set_option('display.max_columns', None)

## Limpieza del Dataset

In [84]:
dataset = pd.read_csv('../Datos/clientes_tarifas_modelo.csv')
dataset.head(10)

Unnamed: 0.1  Unnamed: 0  id_tarifa  consumo_kWh  %consumo_valle  \
0             0           0          0          202               6   
1             1           1          0          279              23   
2             2           2          0          192              36   
3             3           3          0          114              59   
4             4           4          0          206              49   
5             5           5          0          171              35   
6             6           6          0          288              38   
7             7           7          0          120              57   
8             8           8          0          202               2   
9             9           9          0          221              39   

   %consumo_llano  %consumo_punta  %consumo_8h  %consumo_16h compania  \
0              75              19           30            70   Repsol   
1              19              58            1            99   Repsol   
2               3              61           14            86   Repsol   
3              23              18           56            44   Repsol   
4              48               3           74            26   Repsol   
5               5              60           33            67   Repsol   
6              41              21           67            33   Repsol   
7              11              32           74            26   Repsol   
8              17              81           28            72   Repsol   
9              20              41           65            35   Repsol   

         tarifa  tp_punta_euros/kwh/dia  tp_valle_euros/kwh/dia  \
0  Mis 10 Horas                0.068192                0.068192   
1  Mis 10 Horas                0.068192                0.068192   
2  Mis 10 Horas                0.068192                0.068192   
3  Mis 10 Horas                0.068192                0.068192   
4  Mis 10 Horas                0.068192                0.068192   
5  Mis 10 Horas                0.068192                0.068192   
6  Mis 10 Horas                0.068192                0.068192   
7  Mis 10 Horas                0.068192                0.068192   
8  Mis 10 Horas                0.068192                0.068192   
9  Mis 10 Horas                0.068192                0.068192   

   peaje_tran_dist_pot_punta  peaje_tran_dist_pot_valle  peaje_ener_valle_tdc  \
0                   0.008192                   0.000527              0.002752   
1                   0.008192                   0.000527              0.002752   
2                   0.008192                   0.000527              0.002752   
3                   0.008192                   0.000527              0.002752   
4                   0.008192                   0.000527              0.002752   
5                   0.008192                   0.000527              0.002752   
6                   0.008192                   0.000527              0.002752   
7                   0.008192                   0.000527              0.002752   
8                   0.008192                   0.000527              0.002752   
9                   0.008192                   0.000527              0.002752   

   peaje_ener_llano_tdc  peaje_ener_punta_tdc  termino_consumo_euros/kwh/hora  \
0              0.027963              0.076974                             0.0   
1              0.027963              0.076974                             0.0   
2              0.027963              0.076974                             0.0   
3              0.027963              0.076974                             0.0   
4              0.027963              0.076974                             0.0   
5              0.027963              0.076974                             0.0   
6              0.027963              0.076974                             0.0   
7              0.027963              0.076974                             0.0   
8              0.027963              0.076974             

In [85]:
dataset.shape

(2080, 44)

In [86]:
dataset['tipo'].unique()

array(['DH', 'FIJO', 'PVPC', 'TRAMOS'], dtype=object)

In [87]:
# Pasamos a tipo numerico el tipo
label_encoder = LabelEncoder()

# Aplicar LabelEncoder a la columna 'tipo'
dataset['tipo_numerico'] = label_encoder.fit_transform(dataset['tipo'])

In [88]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2080 entries, 0 to 2079
Data columns (total 45 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   Unnamed: 0.1                    2080 non-null   int64  
 1   Unnamed: 0                      2080 non-null   int64  
 2   id_tarifa                       2080 non-null   int64  
 3   consumo_kWh                     2080 non-null   int64  
 4   %consumo_valle                  2080 non-null   int64  
 5   %consumo_llano                  2080 non-null   int64  
 6   %consumo_punta                  2080 non-null   int64  
 7   %consumo_8h                     2080 non-null   int64  
 8   %consumo_16h                    2080 non-null   int64  
 9   compania                        2080 non-null   object 
 10  tarifa                          2080 non-null   object 
 11  tp_punta_euros/kwh/dia          2080 non-null   float64
 12  tp_valle_euros/kwh/dia          20

In [89]:
dataset

Unnamed: 0.1  Unnamed: 0  id_tarifa  consumo_kWh  %consumo_valle  \
0                0           0          0          202               6   
1                1           1          0          279              23   
2                2           2          0          192              36   
3                3           3          0          114              59   
4                4           4          0          206              49   
...            ...         ...        ...          ...             ...   
2075          2075        2075        103          230              72   
2076          2076        2076        103          255              34   
2077          2077        2077        103          134              12   
2078          2078        2078        103          288              11   
2079          2079        2079        103          192              61   

      %consumo_llano  %consumo_punta  %consumo_8h  %consumo_16h  \
0                 75              19           30            70   
1                 19              58            1            99   
2                  3              61           14            86   
3                 23              18           56            44   
4                 48               3           74            26   
...              ...             ...          ...           ...   
2075              11              17           90            10   
2076              62               4           51            49   
2077              22              66           98             2   
2078              33              56           27            73   
2079              12              27           69            31   

            compania        tarifa  tp_punta_euros/kwh/dia  \
0             Repsol  Mis 10 Horas                0.068192   
1             Repsol  Mis 10 Horas                0.068192   
2             Repsol  Mis 10 Horas                0.068192   
3             Repsol  Mis 10 Horas                0.068192   
4             Repsol  Mis 10 Horas                0.068192   
...              ...           ...                     ...   
2075  Aduriz Energia  coste + fija                0.080039   
2076  Aduriz Energia  coste + fija                0.080039   
2077  Aduriz Energia  coste + fija                0.080039   
2078  Aduriz Energia  coste + fija                0.080039   
2079  Aduriz Energia  coste + fija                0.080039   

      tp_valle_euros/kwh/dia  peaje_tran_dist_pot_punta  \
0                   0.068192                   0.008192   
1                   0.068192                   0.008192   
2                   0.068192                   0.008192   
3                   0.068192                   0.008192   
4                   0.068192                   0.008192   
...                      ...                        ...   
2075                0.003141                   0.008192   
2076                0.003141                   0.008192   
2077                0.003141                   0.008192   
2078                0.003141                   0.008192   
2079                0.003141                   0.008192   

      peaje_tran_dist_pot_valle  peaje_ener_valle_tdc  peaje_ener_llano_tdc  \
0                      0.000527              0.002752              0.027963   
1                      0.000527              0.002752              0.027963   
2                      0.000527              0.002752              0.027963   
3                      0.000527              0.002752              0.027963   
4                      0.000527              0.002752              0.027963   
...                         ...                   ...                   ...   
2075                   0.000527              0.002752              0.027963   
2076                   0.000527              0.002752              0.027963   
2077                   0.000527              0.002752              0.027963   
2078                   0.000527              0.002752              0

In [90]:
dataset.isnull().sum()

Unnamed: 0.1                      0
Unnamed: 0                        0
id_tarifa                         0
consumo_kWh                       0
%consumo_valle                    0
%consumo_llano                    0
%consumo_punta                    0
%consumo_8h                       0
%consumo_16h                      0
compania                          0
tarifa                            0
tp_punta_euros/kwh/dia            0
tp_valle_euros/kwh/dia            0
peaje_tran_dist_pot_punta         0
peaje_tran_dist_pot_valle         0
peaje_ener_valle_tdc              0
peaje_ener_llano_tdc              0
peaje_ener_punta_tdc              0
termino_consumo_euros/kwh/hora    0
tc_valle_euros/kwh/hora           0
tc_llano_euros/kwh/hora           0
tc_punta_euros/kwh/hora           0
tc_8h_euros/kwh/hora              0
tc_16h_euros/kwh/hora             0
mercado                           0
tipo                              0
otros                             0
alquiler_equipo_euros/dia   

In [91]:
# Sustituir los nan por 0
dataset['margen_euros/kWh/dia'] = dataset['margen_euros/kWh/dia'].fillna(0)

In [92]:
dataset.isnull().sum()

Unnamed: 0.1                      0
Unnamed: 0                        0
id_tarifa                         0
consumo_kWh                       0
%consumo_valle                    0
%consumo_llano                    0
%consumo_punta                    0
%consumo_8h                       0
%consumo_16h                      0
compania                          0
tarifa                            0
tp_punta_euros/kwh/dia            0
tp_valle_euros/kwh/dia            0
peaje_tran_dist_pot_punta         0
peaje_tran_dist_pot_valle         0
peaje_ener_valle_tdc              0
peaje_ener_llano_tdc              0
peaje_ener_punta_tdc              0
termino_consumo_euros/kwh/hora    0
tc_valle_euros/kwh/hora           0
tc_llano_euros/kwh/hora           0
tc_punta_euros/kwh/hora           0
tc_8h_euros/kwh/hora              0
tc_16h_euros/kwh/hora             0
mercado                           0
tipo                              0
otros                             0
alquiler_equipo_euros/dia   

In [93]:
pd.get_dummies(dataset['mercado'], dtype='int')

Libre  Regulado
0         1         0
1         1         0
2         1         0
3         1         0
4         1         0
...     ...       ...
2075      1         0
2076      1         0
2077      1         0
2078      1         0
2079      1         0

[2080 rows x 2 columns]

In [94]:
dataset['peaje_ener_punta_tdc'].unique()

array([0.076974])

In [95]:
# Creamos los dummies del tipo de mercado

dt = pd.merge(dataset, pd.get_dummies(dataset['mercado'], dtype='int'), left_index=True, right_index=True)


In [96]:
dt

Unnamed: 0.1  Unnamed: 0  id_tarifa  consumo_kWh  %consumo_valle  \
0                0           0          0          202               6   
1                1           1          0          279              23   
2                2           2          0          192              36   
3                3           3          0          114              59   
4                4           4          0          206              49   
...            ...         ...        ...          ...             ...   
2075          2075        2075        103          230              72   
2076          2076        2076        103          255              34   
2077          2077        2077        103          134              12   
2078          2078        2078        103          288              11   
2079          2079        2079        103          192              61   

      %consumo_llano  %consumo_punta  %consumo_8h  %consumo_16h  \
0                 75              19           30            70   
1                 19              58            1            99   
2                  3              61           14            86   
3                 23              18           56            44   
4                 48               3           74            26   
...              ...             ...          ...           ...   
2075              11              17           90            10   
2076              62               4           51            49   
2077              22              66           98             2   
2078              33              56           27            73   
2079              12              27           69            31   

            compania        tarifa  tp_punta_euros/kwh/dia  \
0             Repsol  Mis 10 Horas                0.068192   
1             Repsol  Mis 10 Horas                0.068192   
2             Repsol  Mis 10 Horas                0.068192   
3             Repsol  Mis 10 Horas                0.068192   
4             Repsol  Mis 10 Horas                0.068192   
...              ...           ...                     ...   
2075  Aduriz Energia  coste + fija                0.080039   
2076  Aduriz Energia  coste + fija                0.080039   
2077  Aduriz Energia  coste + fija                0.080039   
2078  Aduriz Energia  coste + fija                0.080039   
2079  Aduriz Energia  coste + fija                0.080039   

      tp_valle_euros/kwh/dia  peaje_tran_dist_pot_punta  \
0                   0.068192                   0.008192   
1                   0.068192                   0.008192   
2                   0.068192                   0.008192   
3                   0.068192                   0.008192   
4                   0.068192                   0.008192   
...                      ...                        ...   
2075                0.003141                   0.008192   
2076                0.003141                   0.008192   
2077                0.003141                   0.008192   
2078                0.003141                   0.008192   
2079                0.003141                   0.008192   

      peaje_tran_dist_pot_valle  peaje_ener_valle_tdc  peaje_ener_llano_tdc  \
0                      0.000527              0.002752              0.027963   
1                      0.000527              0.002752              0.027963   
2                      0.000527              0.002752              0.027963   
3                      0.000527              0.002752              0.027963   
4                      0.000527              0.002752              0.027963   
...                         ...                   ...                   ...   
2075                   0.000527              0.002752              0.027963   
2076                   0.000527              0.002752              0.027963   
2077                   0.000527              0.002752              0.027963   
2078                   0.000527              0.002752              0

In [97]:
# eliminamos las columnas con valor objeto y las que no tienen correlación ya que son valores estaticos para todos, también los datos redundantes como los de los % de consumo

dt.drop(columns=['mercado', 'Libre', 'compania', 'tarifa','tipo','Unnamed: 0','Unnamed: 0.1','id_tarifa', 'impuesto_actual', 'alquiler_equipo_euros/dia','peaje_ener_valle_tdc','peaje_ener_llano_tdc','peaje_ener_punta_tdc','%consumo_valle','%consumo_llano','%consumo_punta','%consumo_8h','%consumo_16h'], inplace=True, errors='ignore')
dt

consumo_kWh  tp_punta_euros/kwh/dia  tp_valle_euros/kwh/dia  \
0             202                0.068192                0.068192   
1             279                0.068192                0.068192   
2             192                0.068192                0.068192   
3             114                0.068192                0.068192   
4             206                0.068192                0.068192   
...           ...                     ...                     ...   
2075          230                0.080039                0.003141   
2076          255                0.080039                0.003141   
2077          134                0.080039                0.003141   
2078          288                0.080039                0.003141   
2079          192                0.080039                0.003141   

      peaje_tran_dist_pot_punta  peaje_tran_dist_pot_valle  \
0                      0.008192                   0.000527   
1                      0.008192                   0.000527   
2                      0.008192                   0.000527   
3                      0.008192                   0.000527   
4                      0.008192                   0.000527   
...                         ...                        ...   
2075                   0.008192                   0.000527   
2076                   0.008192                   0.000527   
2077                   0.008192                   0.000527   
2078                   0.008192                   0.000527   
2079                   0.008192                   0.000527   

      termino_consumo_euros/kwh/hora  tc_valle_euros/kwh/hora  \
0                                0.0                 0.000000   
1                                0.0                 0.000000   
2                                0.0                 0.000000   
3                                0.0                 0.000000   
4                                0.0                 0.000000   
...                              ...                      ...   
2075                             0.0                 0.093282   
2076                             0.0                 0.093282   
2077                             0.0                 0.093282   
2078                             0.0                 0.093282   
2079                             0.0                 0.093282   

      tc_llano_euros/kwh/hora  tc_punta_euros/kwh/hora  tc_8h_euros/kwh/hora  \
0                    0.000000                 0.000000              0.086415   
1                    0.000000                 0.000000              0.086415   
2                    0.000000                 0.000000              0.086415   
3                    0.000000                 0.000000              0.086415   
4                    0.000000                 0.000000              0.086415   
...                       ...                      ...                   ...   
2075                 0.129895                 0.179284              0.000000   
2076                 0.129895                 0.179284              0.000000   
2077                 0.129895                 0.179284              0.000000   
2078                 0.129895                 0.179284              0.000000   
2079                 0.129895                 0.179284              0.000000   

      tc_16h_euros/kwh/hora  otros  bono_social_euro/dia  \
0                   0.17283   0.00                   0.0   
1                   0.17283   0.00                   0.0   
2                   0.17283   0.00                   0.0   
3                   0.17283   0.00                   0.0   
4                   0.17283   0.00                   0.0   
...                     ...    ...                   ...   
2075                0.00000   3.72                   0.0   
2076                0.00000   3.72                   0.0   
2077                0.00000   3.72                   0.0   
2078                0.00000   3.72                   0.0   
2079                0.00000   

In [98]:
# Comprobamos la correlación y que  ya no hay valores nan

dt.corr()

consumo_kWh  tp_punta_euros/kwh/dia  \
consumo_kWh                        1.000000               -0.026483   
tp_punta_euros/kwh/dia            -0.026483                1.000000   
tp_valle_euros/kwh/dia            -0.032585                0.376727   
peaje_tran_dist_pot_punta          0.060756               -0.720330   
peaje_tran_dist_pot_valle          0.060756               -0.720330   
termino_consumo_euros/kwh/hora     0.026931                0.147804   
tc_valle_euros/kwh/hora           -0.013861               -0.243284   
tc_llano_euros/kwh/hora           -0.014066               -0.256087   
tc_punta_euros/kwh/hora           -0.010351               -0.270251   
tc_8h_euros/kwh/hora              -0.023615                0.197951   
tc_16h_euros/kwh/hora             -0.023882                0.200383   
otros                             -0.009129               -0.098089   
bono_social_euro/dia               0.060756               -0.720330   
margen_euros/kWh/dia               0.060756               -0.720330   
consumo_unico                      0.248205                0.143112   
consumo_valle                      0.188796               -0.204493   
consumo_llano                      0.179669               -0.200012   
consumo_punta                      0.177401               -0.226409   
consumo_8h                         0.057868                0.170137   
consumo_16h                        0.053661                0.143748   
consumo_euros_unico                0.248205                0.143112   
consumo_euros_valle                0.183979               -0.171214   
consumo_euros_llano                0.173215               -0.179055   
consumo_euros_punta                0.175833               -0.213456   
consumo_euros_8h                   0.056166                0.172840   
consumo_euros_16h                  0.053536                0.151276   
precio_final                       0.795728               -0.058600   
tipo_numerico                     -0.018491               -0.154044   
Regulado                           0.060756               -0.720330   

                                tp_valle_euros/kwh/dia  \
consumo_kWh                                  -0.032585   
tp_punta_euros/kwh/dia                        0.376727   
tp_valle_euros/kwh/dia                        1.000000   
peaje_tran_dist_pot_punta                    -0.297212   
peaje_tran_dist_pot_valle                    -0.297212   
termino_consumo_euros/kwh/hora                0.139094   
tc_valle_euros/kwh/hora                      -0.133147   
tc_llano_euros/kwh/hora                      -0.166396   
tc_punta_euros/kwh/hora                      -0.177800   
tc_8h_euros/kwh/hora                          0.046001   
tc_16h_euros/kwh/hora                         0.044419   
otros                                        -0.021020   
bono_social_euro/dia                         -0.297212   
margen_euros/kWh/dia                         -0.297212   
consumo_unico                                 0.129182   
consumo_valle                                -0.151827   
consumo_llano                                -0.141138   
consumo_punta                                -0.139784   
consumo_8h                                    0.036177   
consumo_16h                                   0.044924   
consumo_euros_unico                           0.129182   
consumo_euros_valle                          -0.113031   
consumo_euros_llano                          -0.128731   
consumo_euros_punta                          -0.127173   
consumo_euros_8h                              0.034064   
consumo_euros_16h                             0.040756   
precio_final                                 -0.043818   
tipo_numerico                                -0.124277   
Regulado                                     -0.297212   

                                peaje_tran_dist_pot_punta  \
consumo_kWh                                      0.060756   
tp_punta_euros/kwh/dia                

## Random Forest

In [99]:
# declarar X e y
X = dt.drop(columns=['tipo_numerico'])
y = dt['tipo_numerico']

In [100]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [101]:
rnd_clf = RandomForestClassifier(n_estimators=500, max_leaf_nodes=16, max_depth=2,
                                 n_jobs=-1, random_state=42)

In [102]:
rnd_clf.fit(X_train, y_train)
y_pred_rf = rnd_clf.predict(X_test)

In [103]:
# Comprobamos que el split se ha hecho correctamente

print(y_test.mean())
print(y_train.mean())
print(dt['tipo_numerico'].mean())

# Parece bastante razonable

1.7644230769230769
1.7944711538461537
1.7884615384615385


In [104]:
rnd_clf.fit(X_train, y_train)
y_pred_rf = rnd_clf.predict(X_test)

In [106]:
print(confusion_matrix(y_train, rnd_clf.predict(X_train)))
print(accuracy_score(y_train, rnd_clf.predict(X_train)))
print(recall_score(y_train, rnd_clf.predict(X_train), average='macro'))
print(precision_score(y_train, rnd_clf.predict(X_train), average='macro'))

[[146   0   0   0]
 [  0 728   0   0]
 [  0   0 106   6]
 [  0   0   0 678]]
0.9963942307692307
0.9866071428571428
0.9978070175438596


In [107]:
print(confusion_matrix(y_test, rnd_clf.predict(X_test)))
print(accuracy_score(y_test, rnd_clf.predict(X_test)))
print(recall_score(y_test, rnd_clf.predict(X_test), average='macro'))
print(precision_score(y_test, rnd_clf.predict(X_test), average='macro'))

[[ 34   0   0   0]
 [  0 192   0   0]
 [  0   0  27   1]
 [  0   0   0 162]]
0.9975961538461539
0.9910714285714286
0.9984662576687117
